//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cocktail {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cocktail.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s already an instance of a bootstrapper. Only one instance per application can be created..
        /// </summary>
        internal static string BootstrapperAlreadyExists {
            get {
                return ResourceManager.GetString("BootstrapperAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper classes or any of its members must not be decorated with the [Export] attribute.
        /// </summary>
        internal static string BootstrapperMustNotBeDecoratedWithExports {
            get {
                return ResourceManager.GetString("BootstrapperMustNotBeDecoratedWithExports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition is not configured. Composition.Configure must be called before any other public method..
        /// </summary>
        internal static string CompositionHelperIsNotConfigured {
            get {
                return ResourceManager.GetString("CompositionHelperIsNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine type name of instance.
        /// </summary>
        internal static string CouldNotDetermineTypeNameOfInstance {
            get {
                return ResourceManager.GetString("CouldNotDetermineTypeNameOfInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate any instances of contract {0}..
        /// </summary>
        internal static string CouldNotLocateAnyInstancesOfContract {
            get {
                return ResourceManager.GetString("CouldNotLocateAnyInstancesOfContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating an EntityManager during recomposition is not allowed..
        /// </summary>
        internal static string CreatingEntityManagerDuringRecompositionNotAllowed {
            get {
                return ResourceManager.GetString("CreatingEntityManagerDuringRecompositionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlock leaven fox octave fierce embalm navel jollily vessel chisel ramp Susan faded toe.
        /// </summary>
        internal static string DefaultPasswordSalt {
            get {
                return ResourceManager.GetString("DefaultPasswordSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password!.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid use of expired EntityManager. The application&apos;s principal has changed since this EntityManager was last used. Tip: Do not keep references to EntityManagers. Instead, always obtain the current EntityManager through IEntityManagerProvider&lt;T&gt;.Manager..
        /// </summary>
        internal static string InvalidUseOfExpiredEntityManager {
            get {
                return ResourceManager.GetString("InvalidUseOfExpiredEntityManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is already present in this dictionary.
        /// </summary>
        internal static string KeyIsAlreadyPresentInThisDictionary {
            get {
                return ResourceManager.GetString("KeyIsAlreadyPresentInThisDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager tried to fetch data..
        /// </summary>
        internal static string ManagerTriedToFetchData {
            get {
                return ResourceManager.GetString("ManagerTriedToFetchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager tried to save data..
        /// </summary>
        internal static string ManagerTriedToSaveData {
            get {
                return ResourceManager.GetString("ManagerTriedToSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more required assemblies were not probed. Did you modify IdeaBladeConfig.Instance.ProbeAssemblyNames? The following assemblies must be probed: {0}.
        /// </summary>
        internal static string MissingRequiredProbeAssemblies {
            get {
                return ResourceManager.GetString("MissingRequiredProbeAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No EntityManagerProvider found..
        /// </summary>
        internal static string NoEntityManagerProviderFound {
            get {
                return ResourceManager.GetString("NoEntityManagerProviderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probed for EntityManagerDelegate and found {0} matchting exports..
        /// </summary>
        internal static string ProbedForEntityManagerDelegateAndFoundMatch {
            get {
                return ResourceManager.GetString("ProbedForEntityManagerDelegateAndFoundMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probed for EntityManagerDelegate and found no matchting exports..
        /// </summary>
        internal static string ProbedForEntityManagerDelegateAndFoundNoMatch {
            get {
                return ResourceManager.GetString("ProbedForEntityManagerDelegateAndFoundNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probed for IValidationErrorNotification and found {0} matchting exports..
        /// </summary>
        internal static string ProbedForIValidationErrorNotificationAndFoundMatch {
            get {
                return ResourceManager.GetString("ProbedForIValidationErrorNotificationAndFoundMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probed for IValidationErrorNotification and found no matching exports. Will be throwing an exception if validation errors occur..
        /// </summary>
        internal static string ProbedForIValidationErrorNotificationAndFoundNoMatch {
            get {
                return ResourceManager.GetString("ProbedForIValidationErrorNotificationAndFoundNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probed for service with contract {0} and found {1}.
        /// </summary>
        internal static string ProbedForServiceAndFoundMatch {
            get {
                return ResourceManager.GetString("ProbedForServiceAndFoundMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probed for service with contract {0} and found multiple matching exports.
        /// </summary>
        internal static string ProbedForServiceAndFoundMultipleMatches {
            get {
                return ResourceManager.GetString("ProbedForServiceAndFoundMultipleMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probed for service with contract {0} and found no matching exports.
        /// </summary>
        internal static string ProbedForServiceFoundNoMatch {
            get {
                return ResourceManager.GetString("ProbedForServiceFoundNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EntityManagerProvider hasn&apos;t been initialized. Please make sure to call EntityManagerProvider.Initialize before executing the first query.
        /// </summary>
        internal static string TheEntityManagerProviderHasNotBeenInitialized {
            get {
                return ResourceManager.GetString("TheEntityManagerProviderHasNotBeenInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EntityManagerProvider is not returning a valid EntityManager. Please check the implementation..
        /// </summary>
        internal static string TheEntityManagerProviderIsNotReturningValidEntityManager {
            get {
                return ResourceManager.GetString("TheEntityManagerProviderIsNotReturningValidEntityManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The persistence layer failed to initialize.
        /// </summary>
        internal static string ThePersistenceLayerFailedToInitialize {
            get {
                return ResourceManager.GetString("ThePersistenceLayerFailedToInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This EntityManager is currently busy with a previous SaveChangeAsync call..
        /// </summary>
        internal static string ThisEntityManagerIsCurrentlyBusyWithAPreviousSaveChangeAsync {
            get {
                return ResourceManager.GetString("ThisEntityManagerIsCurrentlyBusyWithAPreviousSaveChangeAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain user credential.
        /// </summary>
        internal static string UnableToObtainUserCredential {
            get {
                return ResourceManager.GetString("UnableToObtainUserCredential", resourceCulture);
            }
        }
    }
}
