//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cocktail {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cocktail.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper classes or any of its members must not be decorated with the [Export] attribute.
        /// </summary>
        internal static string BootstrapperMustNotBeDecoratedWithExports {
            get {
                return ResourceManager.GetString("BootstrapperMustNotBeDecoratedWithExports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current asynchronous operation cannot be cancelled..
        /// </summary>
        internal static string CannotCancelCurrentOperation {
            get {
                return ResourceManager.GetString("CannotCancelCurrentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null is not a valid CompositionProvider..
        /// </summary>
        internal static string CompositionProviderCannotBeNull {
            get {
                return ResourceManager.GetString("CompositionProviderCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first set a valid CompositionProvider by using Composition.SetProvider..
        /// </summary>
        internal static string CompositionProviderNotConfigured {
            get {
                return ResourceManager.GetString("CompositionProviderNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the ConnectionOptions returned by IConnectionOptionsResolver: {0} does not match the value of the name parameter: {1}..
        /// </summary>
        internal static string ConnectionOptionsNameMissmatch {
            get {
                return ResourceManager.GetString("ConnectionOptionsNameMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current ConnectionOptions doesn&apos;t have a name yet. Use WithName to assign a name..
        /// </summary>
        internal static string ConnectionOptionsNoNameYet {
            get {
                return ResourceManager.GetString("ConnectionOptionsNoNameYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find ConnectionOptions with the name: {0}..
        /// </summary>
        internal static string ConnectionOptionsNotFound {
            get {
                return ResourceManager.GetString("ConnectionOptionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine type name of instance.
        /// </summary>
        internal static string CouldNotDetermineTypeNameOfInstance {
            get {
                return ResourceManager.GetString("CouldNotDetermineTypeNameOfInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate any instances of contract {0}..
        /// </summary>
        internal static string CouldNotLocateAnyInstancesOfContract {
            get {
                return ResourceManager.GetString("CouldNotLocateAnyInstancesOfContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating an EntityManager during recomposition is not allowed..
        /// </summary>
        internal static string CreatingEntityManagerDuringRecompositionNotAllowed {
            get {
                return ResourceManager.GetString("CreatingEntityManagerDuringRecompositionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentState is only supported in a Control type..
        /// </summary>
        internal static string CurrentStateOnlySupportedInControls {
            get {
                return ResourceManager.GetString("CurrentStateOnlySupportedInControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlock leaven fox octave fierce embalm navel jollily vessel chisel ramp Susan faded toe.
        /// </summary>
        internal static string DefaultPasswordSalt {
            get {
                return ResourceManager.GetString("DefaultPasswordSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This dictionary is read-only..
        /// </summary>
        internal static string DictionaryIsReadOnly {
            get {
                return ResourceManager.GetString("DictionaryIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary image data is neither jpeg nor png..
        /// </summary>
        internal static string InvalidBinaryImageData {
            get {
                return ResourceManager.GetString("InvalidBinaryImageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password!.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid use of expired EntityManager. The application&apos;s principal has changed since this EntityManager was last used. Tip: Do not keep references to EntityManagers. Instead, always obtain the current EntityManager through IEntityManagerProvider&lt;T&gt;.Manager..
        /// </summary>
        internal static string InvalidUseOfExpiredEntityManager {
            get {
                return ResourceManager.GetString("InvalidUseOfExpiredEntityManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is already present in this dictionary.
        /// </summary>
        internal static string KeyIsAlreadyPresentInThisDictionary {
            get {
                return ResourceManager.GetString("KeyIsAlreadyPresentInThisDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout failed with the following error: {0}. Error was ignored..
        /// </summary>
        internal static string LogoutFailed {
            get {
                return ResourceManager.GetString("LogoutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager tried to fetch data..
        /// </summary>
        internal static string ManagerTriedToFetchData {
            get {
                return ResourceManager.GetString("ManagerTriedToFetchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager tried to save data..
        /// </summary>
        internal static string ManagerTriedToSaveData {
            get {
                return ResourceManager.GetString("ManagerTriedToSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a new instance of {0}. The type does not have a parameterless constructor..
        /// </summary>
        internal static string MissingDefaultConstructor {
            get {
                return ResourceManager.GetString("MissingDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create an instance of EntityManager: {0}. Required constructor not found. Please add the following constructor: public {0}(IdeaBlade.EntityModel.EntityManagerContext)..
        /// </summary>
        internal static string MissingEntityManagerConstructor {
            get {
                return ResourceManager.GetString("MissingEntityManagerConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The navigation is not in a valid state to be started..
        /// </summary>
        internal static string NavigationNotInValidState {
            get {
                return ResourceManager.GetString("NavigationNotInValidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current NavigationService doesn&apos;t manage its own navigation history..
        /// </summary>
        internal static string NavigationServiceDoesNotManageHistory {
            get {
                return ResourceManager.GetString("NavigationServiceDoesNotManageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No EntityManagerProvider found..
        /// </summary>
        internal static string NoEntityManagerProviderFound {
            get {
                return ResourceManager.GetString("NoEntityManagerProviderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No export found for {0}.
        /// </summary>
        internal static string NoExportFound {
            get {
                return ResourceManager.GetString("NoExportFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveWatch was called without a matching AddWatch call..
        /// </summary>
        internal static string NoMatchingAddWatch {
            get {
                return ResourceManager.GetString("NoMatchingAddWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to initialize or reset the fake backing store on a non-suitable EntityManagerProvider. Ensure that the EntityManagerProvider uses the correct ConnectionOptions..
        /// </summary>
        internal static string NonSuitableEmpForFakeStoreOperation {
            get {
                return ResourceManager.GetString("NonSuitableEmpForFakeStoreOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameterless constructor defined for this object..
        /// </summary>
        internal static string NoParameterlessCtor {
            get {
                return ResourceManager.GetString("NoParameterlessCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another page change is in progress. You must wait before attempting another page change..
        /// </summary>
        internal static string PageChangeInProgress {
            get {
                return ResourceManager.GetString("PageChangeInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another navigation is pending..
        /// </summary>
        internal static string PendingNavigation {
            get {
                return ResourceManager.GetString("PendingNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probed for EntityManagerDelegate and found {0} matchting exports..
        /// </summary>
        internal static string ProbedForEntityManagerDelegateAndFoundMatch {
            get {
                return ResourceManager.GetString("ProbedForEntityManagerDelegateAndFoundMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probed for EntityManagerDelegate and found no matchting exports..
        /// </summary>
        internal static string ProbedForEntityManagerDelegateAndFoundNoMatch {
            get {
                return ResourceManager.GetString("ProbedForEntityManagerDelegateAndFoundNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probed for IValidationErrorNotification and found {0} matchting exports..
        /// </summary>
        internal static string ProbedForIValidationErrorNotificationAndFoundMatch {
            get {
                return ResourceManager.GetString("ProbedForIValidationErrorNotificationAndFoundMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probed for IValidationErrorNotification and found no matching exports. Will be throwing an exception if validation errors occur..
        /// </summary>
        internal static string ProbedForIValidationErrorNotificationAndFoundNoMatch {
            get {
                return ResourceManager.GetString("ProbedForIValidationErrorNotificationAndFoundNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probed for service with contract {0} and found {1}.
        /// </summary>
        internal static string ProbedForServiceAndFoundMatch {
            get {
                return ResourceManager.GetString("ProbedForServiceAndFoundMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probed for service with contract {0} and found multiple matching exports.
        /// </summary>
        internal static string ProbedForServiceAndFoundMultipleMatches {
            get {
                return ResourceManager.GetString("ProbedForServiceAndFoundMultipleMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probed for service with contract {0} and found no matching exports.
        /// </summary>
        internal static string ProbedForServiceFoundNoMatch {
            get {
                return ResourceManager.GetString("ProbedForServiceFoundNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected only one entity of type: {0}, with query: {1}, but found: {2}.
        /// </summary>
        internal static string ShouldHaveExactlyOneEntityErrorMessage {
            get {
                return ResourceManager.GetString("ShouldHaveExactlyOneEntityErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created new instance of EntityManager: {0} with connection info: {1}, IsFake={2}..
        /// </summary>
        internal static string SuccessfullyCreatedEntityManager {
            get {
                return ResourceManager.GetString("SuccessfullyCreatedEntityManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully performed user login with connection info: {0}, IsFake={1}..
        /// </summary>
        internal static string SuccessfullyLoggedIn {
            get {
                return ResourceManager.GetString("SuccessfullyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target type must be System.Windows.Media.ImageSource..
        /// </summary>
        internal static string TargetTypeMustBeImageSource {
            get {
                return ResourceManager.GetString("TargetTypeMustBeImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Fake Store has not been initialized..
        /// </summary>
        internal static string TheFakeStoreHasNotBeenInitialized {
            get {
                return ResourceManager.GetString("TheFakeStoreHasNotBeenInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This EntityManager is currently busy with a previous SaveChangeAsync call..
        /// </summary>
        internal static string ThisEntityManagerIsCurrentlyBusyWithAPreviousSaveChangeAsync {
            get {
                return ResourceManager.GetString("ThisEntityManagerIsCurrentlyBusyWithAPreviousSaveChangeAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No view was found for {0}. See the log for searched views..
        /// </summary>
        internal static string ViewNotFound {
            get {
                return ResourceManager.GetString("ViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
